export const html = require("./html5-icon.png")
export const css = require("./css-icon.png")
export const js = require("./js-icon.png")
export const react = require("./react-icon.png")
export const bootstrap = require("./Bootstrap-icon.png")
export const jquery = require("./jquery-icon.png")

export const node = require("./nodejs-icon.svg")
export const express = require("./ExpressJS-logo.png")
export const flask = require("./flask-icon.png")

export const python = require("./python-icon.png")
export const cLang = require("./C-lang-icon.png")
export const cPlus = require("./C-Plus-icon.png")
export const java = require("./java-icon.png")

export const mysql = require("./mysql-icon.png")
export const mongodb = require("./mongodb-icon.png")
export const postgresql = require("./postgresql-icon.png")
export const dynamboDB = require("./DynamoDB-icon.png")
